export enum TenantStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  SUSPENDED = 'SUSPENDED',
  LOCKED = 'LOCKED',
  PENDING_DELETION = 'PENDING_DELETION',
  DELETED = 'DELETED',
  GRACE_PERIOD = 'GRACE_PERIOD',
}
