/**
 * Platform audit log action types
 */
export enum PlatformAction {
  // Tenant actions
  TENANT_CREATED = 'TENANT_CREATED',
  TENANT_UPDATED = 'TENANT_UPDATED',
  TENANT_DELETED = 'TENANT_DELETED',
  TENANT_SUSPENDED = 'TENANT_SUSPENDED',
  TENANT_REACTIVATED = 'TENANT_REACTIVATED',
  TENANT_LOCKED = 'TENANT_LOCKED',
  TENANT_UNLOCKED = 'TENANT_UNLOCKED',

  // Billing actions
  SUBSCRIPTION_CHANGED = 'SUBSCRIPTION_CHANGED',
  SUBSCRIPTION_CANCELLED = 'SUBSCRIPTION_CANCELLED',
  REFUND_ISSUED = 'REFUND_ISSUED',
  CREDIT_APPLIED = 'CREDIT_APPLIED',

  // Support actions
  IMPERSONATION_STARTED = 'IMPERSONATION_STARTED',
  IMPERSONATION_ENDED = 'IMPERSONATION_ENDED',
  SUPPORT_CASE_CREATED = 'SUPPORT_CASE_CREATED',
  TIME_ENTRY_UPDATED = 'TIME_ENTRY_UPDATED',

  // Security actions
  FORCE_PASSWORD_RESET = 'FORCE_PASSWORD_RESET',
  SESSIONS_REVOKED = 'SESSIONS_REVOKED',
  SECURITY_POLICY_UPDATED = 'SECURITY_POLICY_UPDATED',
  IP_ALLOWLIST_UPDATED = 'IP_ALLOWLIST_UPDATED',

  // Compliance actions
  DATA_EXPORTED = 'DATA_EXPORTED',
  DATA_DELETED = 'DATA_DELETED',
  GDPR_REQUEST_PROCESSED = 'GDPR_REQUEST_PROCESSED',

  // Operations
  FEATURE_FLAG_UPDATED = 'FEATURE_FLAG_UPDATED',
  RATE_LIMIT_UPDATED = 'RATE_LIMIT_UPDATED',
  CACHE_CLEARED = 'CACHE_CLEARED',

  // Platform user management
  PLATFORM_USER_CREATED = 'PLATFORM_USER_CREATED',
  PLATFORM_USER_UPDATED = 'PLATFORM_USER_UPDATED',
  PLATFORM_USER_DELETED = 'PLATFORM_USER_DELETED',
  PLATFORM_USER_ROLE_CHANGED = 'PLATFORM_USER_ROLE_CHANGED',
}
