export enum PlatformRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  SUPPORT_ADMIN = 'SUPPORT_ADMIN',
  BILLING_ADMIN = 'BILLING_ADMIN',
  COMPLIANCE_ADMIN = 'COMPLIANCE_ADMIN',
  SECURITY_ADMIN = 'SECURITY_ADMIN',
  ANALYTICS_VIEWER = 'ANALYTICS_VIEWER',
}
