/** Shared sensitive field names for log redaction (case-insensitive substring match). */
export const SENSITIVE_KEYS = [
  'password',
  'passwordHash',
  'password_hash',
  'secret',
  'token',
  'accessToken',
  'access_token',
  'refreshToken',
  'refresh_token',
  'authorization',
  'bearer',
  'apiKey',
  'api_key',
  'vault',
  'email',
  'phone',
  'ssn',
  'socialSecurity',
  'social_security',
  'creditCard',
  'credit_card',
  'cardNumber',
  'card_number',
  'cvv',
  'accountNumber',
  'account_number',
  'routingNumber',
  'routing_number',
  'dob',
  'dateOfBirth',
  'date_of_birth',
  'birthDate',
  'birth_date',
  'ipAddress',
  'ip_address',
] as const;

export const PII_FIELD_PATTERNS: string[] = SENSITIVE_KEYS.map((key) => key.toLowerCase().replace(/[^a-z0-9]/g, ''));
